version: 2.1

executors:
  example:
    docker:
      - image: circleci/openjdk:8-jdk
        #se debe ejecutar el comando xvfb en el contenedor de docker.

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: example
          command: -Dtest=UnitTest test