version: 2.1

executors:
  example:
    docker:
      - image: circleci/openjdk:8-jdk

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: example
          command: xvfb:1 1920x1080x16