version: 2.1

executors:
  example:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      MAVEN_OPTS: -Djava.awt.headless=true

orbs:
  maven: circleci/maven@1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: example
